export const sampleWords = [
  { text: "abandon", meaning: "放弃；抛弃", example: "He had to abandon the plan." },
  { text: "benefit", meaning: "益处；使受益", example: "Exercise benefits your health." },
  { text: "capture", meaning: "捕获；吸引", example: "The photo captured the moment." },
  { text: "delay", meaning: "延迟；耽搁", example: "The flight was delayed." },
  { text: "efficient", meaning: "高效的", example: "She is efficient at work." },
  { text: "feature", meaning: "特征；以…为特色", example: "The app features offline mode." },
  { text: "generate", meaning: "生成；产生", example: "The machine generates power." },
  { text: "habit", meaning: "习惯", example: "Reading is a good habit." },
  { text: "identify", meaning: "识别；确认", example: "Can you identify the problem?" },
  { text: "journey", meaning: "旅程", example: "It was a long journey." },
  { text: "knowledge", meaning: "知识", example: "Knowledge is power." },
  { text: "limit", meaning: "限制", example: "There is a limit to what we can do." },
  { text: "maintain", meaning: "保持；维护", example: "Maintain a healthy lifestyle." },
  { text: "notice", meaning: "注意到；通知", example: "Did you notice the change?" },
  { text: "obvious", meaning: "明显的", example: "It’s obvious that he is tired." },
  { text: "practice", meaning: "练习；实践", example: "Practice makes perfect." },
  { text: "quality", meaning: "质量；品质", example: "We focus on quality." },
  { text: "recover", meaning: "恢复；康复", example: "He recovered quickly." },
  { text: "schedule", meaning: "日程；安排", example: "Let’s check the schedule." },
  { text: "target", meaning: "目标；针对", example: "We target young users." },
  { text: "unique", meaning: "独特的", example: "Each person is unique." },
  { text: "value", meaning: "价值；重视", example: "I value your time." },
  { text: "willing", meaning: "愿意的", example: "She is willing to help." },
  { text: "achieve", meaning: "实现；达成", example: "You can achieve your goals." },
  { text: "balance", meaning: "平衡", example: "Keep a balance between work and life." },
  { text: "confirm", meaning: "确认", example: "Please confirm your email." },
  { text: "deliver", meaning: "交付；递送", example: "We deliver within 24 hours." },
  { text: "enhance", meaning: "增强；提升", example: "This will enhance performance." },
  { text: "focus", meaning: "专注；焦点", example: "Focus on the key points." },
  { text: "improve", meaning: "改进；提升", example: "I want to improve my English." },
];

